name: Daily Auto Commit

on:
  schedule:
    - cron: '0 18 * * *'  # Runs daily at 6 PM UTC
  workflow_dispatch:      # Allows manual triggering

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Make daily update (append timestamp)
        run: |
          echo "Updated on $(date -u)" >> daily-log.txt

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Daily auto-commit: $(date -u)" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
